version: 2
jobs:
  build:
    working_directory: /go/src/github.com/segmentio/specs
    docker:
      - image: node:6
    steps:
      - checkout
      - restore_cache:
          key: dev-dependency-cache-{{ checksum "package-lock.json" }}
      - run: make node_modules
      - save_cache:
          key: dev-dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules

  publish:
    working_directory: /go/src/github.com/segmentio/specs
    docker:
      - image: node:6
    steps:
      - checkout
      - restore_cache:
          key: dev-dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Authenticate with AWS and Docker
          command: |
            apt-get update && apt-get install python-dev
            curl -O https://bootstrap.pypa.io/get-pip.py && python get-pip.py
            pip install awscli==1.11.91
            aws ecr get-login --no-include-email --region $AWS_REGION | sh
            docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS

      - run:
          name: Build and Publish Docker Images
          command: |
            docker build -t segment/specs .
            docker push segment/specs:latest
            docker tag segment/specs:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/specs:latest
            docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/specs:latest

workflows:
  version: 2
  build-and-publish:
    jobs:
      - build
      - publish:
          filters:
            branches:
              only:
                - master
                - systemizer/fix-publish
